name: Sync to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Trae todo el historial para evitar errores de Git

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install huggingface_hub

      - name: Ejecutar sincronización
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python upload_model.py

