name: Sync to Hugging Face

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'data/raw/audio_input/**' # No activar si solo subes MP3 (esperar al entrenamiento)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Instalar dependencias
        run: pip install huggingface_hub

      - name: Ejecutar sincronización
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python upload_model.py

